version: '3.7'

networks:
  algorithms:
    name: algorithms
    external: true

services:
  pytest:
    build:
      context: ./docker
      dockerfile: DockerFile
    volumes:
      - ./src:/src
    working_dir: /src/
    networks:
      - algorithms
  

